### ISSUE TITLE
Cannot find module '../lightningcss.linux-x64-gnu.node'

### ISSUE THREAD

**Issue by stevenpetryk** [parcel-bundler/lightningcss#279]
Hey there, just trying to use Lightning CSS as a minifier to unlock some sweet speed-ups in CI. I'm noticing that LightningCSS runs just fine locally (Apple Silicon), but is failing in CI with the following error:

```
[2022-09-09T20:29:27Z] Error: Cannot find module '../lightningcss.linux-x64-gnu.node'
  | [2022-09-09T20:29:27Z] Require stack:
  | [2022-09-09T20:29:27Z] - /app/x/node_modules/lightningcss/node/index.js
  | [2022-09-09T20:29:27Z] - /app/x/node_modules/css-minimizer-webpack-plugin/dist/minify.js
  | [2022-09-09T20:29:27Z] - /app/x/node_modules/css-minimizer-webpack-plugin/node_modules/jest-worker/build/workers/threadChild.js
  | [2022-09-09T20:29:27Z]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
  | [2022-09-09T20:29:27Z]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
  | [2022-09-09T20:29:27Z]     at Module.require (internal/modules/cjs/loader.js:974:19)
  | [2022-09-09T20:29:27Z]     at require (internal/modules/cjs/helpers.js:92:18)
  | [2022-09-09T20:29:27Z]     at Object.<anonymous> (/app/x/node_modules/lightningcss/node/index.js:21:22)
  | [2022-09-09T20:29:27Z]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
  | [2022-09-09T20:29:27Z]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
  | [2022-09-09T20:29:27Z]     at Module.load (internal/modules/cjs/loader.js:950:32)
  | [2022-09-09T20:29:27Z]     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
  | [2022-09-09T20:29:27Z]     at Module.require (internal/modules/cjs/loader.js:974:19)

```

This is of course from this part of the code:

```ts
try {
  module.exports = require(`lightningcss-${parts.join('-')}`);
} catch (err) {
  console.error(error);
  module.exports = require(`../lightningcss.${parts.join('-')}.node`);
}
```

I'm pretty sure that `lightningcss-linux-x64-gnu` should be getting installed—when I look at the `yarn install` logs, I see that every _other_ platform is failing successfully:

```
info lightningcss-darwin-arm64@1.14.0: The platform "linux" is incompatible with this module.
info "lightningcss-darwin-arm64@1.14.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info lightningcss-darwin-arm64@1.14.0: The CPU architecture "x64" is incompatible with this module.
info lightningcss-darwin-x64@1.14.0: The platform "linux" is incompatible with this module.
info "lightningcss-darwin-x64@1.14.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info lightningcss-linux-arm-gnueabihf@1.14.0: The CPU architecture "x64" is incompatible with this module.
info "lightningcss-linux-arm-gnueabihf@1.14.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info lightningcss-linux-arm64-gnu@1.14.0: The CPU architecture "x64" is incompatible with this module.
info "lightningcss-linux-arm64-gnu@1.14.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info lightningcss-linux-arm64-musl@1.14.0: The CPU architecture "x64" is incompatible with this module.
info "lightningcss-linux-arm64-musl@1.14.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info lightningcss-win32-x64-msvc@1.14.0: The platform "linux" is incompatible with this module.
info "lightningcss-win32-x64-msvc@1.14.0" is an optional dependency and failed compatibility check. Excluding it from installation.
```

---

I'm adding some logs (using patch-package) around what `parts` is becoming, but I'd like to flag this in case it is affecting others. Notably, this issue doesn't seem to be affecting SWC, so maybe there's some disparity there.

**Comment by stevenpetryk** [comment]
I think it might also be useful to know the intention behind the try / catch statement :)

**Comment by stevenpetryk** [comment]
Hmm, so `parts` does end up being `['linux', 'x64', 'gnu']`, which means that it is attempting to require and failing to find `lightningcss-linux-x64-gnu`. Perhaps that really isn't getting installed somehow. I'll keep investigating.

**Comment by devongovett** [comment]
The try catch is for local development where the platform-specific package isn't installed. Would be good to know what packages are installed on your machine. What OS/CPU architecture are your CI machines running?

**Comment by stevenpetryk** [comment]
From what I can tell (I'm having to do a little digging here to figure out our setup), it's a docker image ultimately based on [node:14.17.3-buster](https://hub.docker.com/layers/library/node/14.17.3-buster/images/sha256-c62d50647fab25d58385da6b952e5988a9a89db357de62dd7f5c6bd7f06c7954?context=explore). I'll take a look and see if I can reproduce it in a clean container.

**Comment by stevenpetryk** [comment]
The plot thickens: I was able to add some logging around the entire contents of `node_modules` and found that `lightningcss` is getting installed, but none of the native dependencies. And yet the only failed optionaldependency installations were the ones in those logs. 

Anyway, I'm getting increasingly sure that there's nothing wrong with lightningcss here, so I'll close this issue. I will still post an update if I figure something out either way for future folks.

**Comment by stevenpetryk** [comment]
Just updating to round this out: found out that our CI boxes run `yarn install` with `--ignore-optional` 😓 so of course the optional deps weren't installing

**Comment by AidanNelson** [comment]
I'm facing this same issue on an Ubuntu 18.04 system.  

``` bash
@parcel/transformer-css: Could not resolve module "/my-project-folder/node_modules/lightningcss/lightningcss.linux-x64-gnu.node" from 
"/my-project-folder/node_modules/lightningcss/node/index.js"
```

Any clue how to solve it?  I am running node version 16.18.0 and npm version 8.19.2.

**Comment by ipmb** [comment]
I'm not sure this should be closed. I can replicate this on a project using this `Dockerfile`:

```dockerfile
FROM node:18-bullseye as build-node

WORKDIR /app
COPY package-lock.json package.json .parcelrc tsconfig.json ./
RUN set -ex && npm install -g npm@latest && npm ci
COPY static/ ./static
RUN set -ex && npm run build  # alias to `parcel build`
```

Building on ARM works fine. My expectation is that it also works on amd64, but building with `docker build --platform linux/amd64` results in the same error as above:

```
=> ERROR [build-node 6/6] RUN set -ex && npm run build                                                            9.7s
------
 > [build-node 6/6] RUN set -ex && npm run build:
#10 0.143 + npm run build
#10 2.707
#10 2.707 > lincolnloop@0.0.1 build
#10 2.707 > parcel build
#10 2.707
#10 6.384 Building...
#10 8.837 🚨 Build failed.
#10 8.847
#10 8.855 @parcel/transformer-css: Could not resolve module
#10 8.855 "/app/node_modules/lightningcss/lightningcss.linux-x64-gnu.node" from
#10 8.855 "/app/node_modules/lightningcss/node/index.js"
#10 8.856
#10 8.867   Error: Could not resolve module
#10 8.867   "/app/node_modules/lightningcss/lightningcss.linux-x64-gnu.node" from
#10 8.867   "/app/node_modules/lightningcss/node/index.js"
#10 8.867       at $0578d0f6e116167e$export$fb2a0b866a8162dc.resolve
#10 8.867   (/app/node_modules/@parcel/package-manager/lib/index.js:4991:21)
#10 8.867       at NodePackageManager.resolveSync
#10 8.867   (/app/node_modules/@parcel/package-manager/lib/index.js:3510:42)
#10 8.867       at NodePackageManager.requireSync
#10 8.867   (/app/node_modules/@parcel/package-manager/lib/index.js:3352:34)
#10 8.867       at m.require
#10 8.867   (/app/node_modules/@parcel/package-manager/lib/index.js:3366:25)
#10 8.867       at require (node:internal/modules/cjs/helpers:103:18)
#10 8.867       at Object.<anonymous> (/app/node_modules/lightningcss/node/index.js:21:22)
#10 8.867       at Module._compile (node:internal/modules/cjs/loader:1226:14)
#10 8.867       at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
#10 8.867       at Module.load (node:internal/modules/cjs/loader:1089:32)
#10 8.867       at NodePackageManager.load
#10 8.867   (/app/node_modules/@parcel/package-manager/lib/index.js:3375:15)
#10 8.867
```

here are the relevant lines for `lightningcss` in `package-lock.json`:

```json
    "node_modules/lightningcss": {
      "version": "1.18.0",
      "dev": true,
      "license": "MPL-2.0",
      "dependencies": {
        "detect-libc": "^1.0.3"
      },
      "engines": {
        "node": ">= 12.0.0"
      },
      "funding": {
        "type": "opencollective",
        "url": "https://opencollective.com/parcel"
      },
      "optionalDependencies": {
        "lightningcss-darwin-arm64": "1.18.0",
        "lightningcss-darwin-x64": "1.18.0",
        "lightningcss-linux-arm-gnueabihf": "1.18.0",
        "lightningcss-linux-arm64-gnu": "1.18.0",
        "lightningcss-linux-arm64-musl": "1.18.0",
        "lightningcss-linux-x64-gnu": "1.18.0",
        "lightningcss-linux-x64-musl": "1.18.0",
        "lightningcss-win32-x64-msvc": "1.18.0"
      }
    },
    "node_modules/lightningcss-linux-arm64-gnu": {
      "version": "1.18.0",
      "cpu": [
        "arm64"
      ],
      "dev": true,
      "license": "MPL-2.0",
      "optional": true,
      "os": [
        "linux"
      ],
      "engines": {
        "node": ">= 12.0.0"
      },
      "funding": {
        "type": "opencollective",
        "url": "https://opencollective.com/parcel"
      }
    },
    "node_modules/lightningcss-linux-arm64-musl": {
      "version": "1.18.0",
      "cpu": [
        "arm64"
      ],
      "dev": true,
      "license": "MPL-2.0",
      "optional": true,
      "os": [
        "linux"
      ],
      "engines": {
        "node": ">= 12.0.0"
      },
      "funding": {
        "type": "opencollective",
        "url": "https://opencollective.com/parcel"
      }
    },
```

**Comment by devongovett** [comment]
Did any of the optional dependencies get installed?

**Comment by ipmb** [comment]
Yes. If I remove the `npm run build` step, this is what I get in the `linux/amd64` container:

```
$ jq '.packages | with_entries(select(.value.optional == true)) | keys' package-lock.json
[
  "node_modules/@lmdb/lmdb-linux-arm64",
  "node_modules/@msgpackr-extract/msgpackr-extract-linux-arm64",
  "node_modules/encoding",
  "node_modules/iconv-lite",
  "node_modules/lightningcss-linux-arm64-gnu",
  "node_modules/lightningcss-linux-arm64-musl",
  "node_modules/msgpackr-extract",
  "node_modules/safer-buffer"
]
$ find node_modules -type d -name encoding -or -name iconv-lite -or -name 'lightningcss*'
node_modules/encoding
node_modules/iconv-lite
node_modules/lightningcss
```

On the`linux/arm64` image, I also get `node_modules/lightningcss-linux-arm64-gnu` and `node_modules/lightningcss-linux-arm64-musl`.

**Comment by devongovett** [comment]
Looks like lightningcss-linux-arm64-gnu appeared in the package-lock but not actually installed in node_modules then?

**Comment by ipmb** [comment]
Correct, the `arm64` variant isn't getting installed on `amd64`. I presume it wouldn't work there anyway. It seems like the package-lock should contain both `arm64` and `amd64` and then `npm` will install the one for the current architecture?

**Comment by devongovett** [comment]
Right, but npm is also not installing the x86 variant it seems. I guess amd64 is the same thing as x86_64?
