### ISSUE TITLE
Installation fails on docker desktop on windows/WSL2

### ISSUE THREAD

**Issue by mhlakhani** [parcel-bundler/lightningcss#354]
Hi! 

I started using the bundler and I'm really happy with the results so far. However, I'm having trouble installing the CLI when creating a docker image. I'm using Docker Desktop in windows via WSL2. 

Installing it within WSL2 directly works fine so I don't think it's a host issue.

My docker version is `Docker version 20.10.16, build aa7e414`

Here's the snippet I used in my dockerfile:

```
# select build image
FROM rust:latest as build

# install dependencies
RUN USER=root curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN USER=root apt-get install -y libssl-dev pkg-config libsqlite3-dev nodejs
RUN USER=root npm install --global sass 
RUN USER=root npm install --global lightningcss-cli
```

This fails with:

```
 > [build  4/58] RUN USER=root npm install --global sass lightningcss-cli:
#9 3.679 /usr/bin/lightningcss -> /usr/lib/node_modules/lightningcss-cli/lightningcss
#9 3.681 /usr/bin/sass -> /usr/lib/node_modules/sass/sass.js
#9 3.686
#9 3.686 > lightningcss-cli@1.17.1 postinstall /usr/lib/node_modules/lightningcss-cli
#9 3.686 > node postinstall.js
#9 3.686
#9 3.744 Failed to move lightningcss-cli binary into place.
#9 3.759 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-cli-darwin-arm64@1.17.1 (node_modules/lightningcss-cli/node_modules/lightningcss-cli-darwin-arm64):
#9 3.759 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-cli-darwin-arm64@1.17.1: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
#9 3.764 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-cli-darwin-x64@1.17.1 (node_modules/lightningcss-cli/node_modules/lightningcss-cli-darwin-x64):
#9 3.764 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-cli-darwin-x64@1.17.1: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
#9 3.771 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-cli-win32-x64-msvc@1.17.1 (node_modules/lightningcss-cli/node_modules/lightningcss-cli-win32-x64-msvc):
#9 3.771 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-cli-win32-x64-msvc@1.17.1: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
#9 3.775 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-cli-linux-arm64-gnu@1.17.1 (node_modules/lightningcss-cli/node_modules/lightningcss-cli-linux-arm64-gnu):
#9 3.775 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-cli-linux-arm64-gnu@1.17.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
#9 3.779 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-cli-linux-arm-gnueabihf@1.17.1 (node_modules/lightningcss-cli/node_modules/lightningcss-cli-linux-arm-gnueabihf):
#9 3.779 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-cli-linux-arm-gnueabihf@1.17.1: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
#9 3.783 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-cli-linux-arm64-musl@1.17.1 (node_modules/lightningcss-cli/node_modules/lightningcss-cli-linux-arm64-musl):
#9 3.783 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-cli-linux-arm64-musl@1.17.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
#9 3.788 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/sass/node_modules/chokidar/node_modules/fsevents):
#9 3.788 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
#9 3.788
#9 3.800 npm ERR! code ELIFECYCLE
#9 3.800 npm ERR! errno 1
#9 3.802 npm ERR! lightningcss-cli@1.17.1 postinstall: `node postinstall.js`
#9 3.802 npm ERR! Exit status 1
#9 3.802 npm ERR!
#9 3.802 npm ERR! Failed at the lightningcss-cli@1.17.1 postinstall script.
#9 3.802 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#9 3.811
#9 3.811 npm ERR! A complete log of this run can be found in:
#9 3.811 npm ERR!     /root/.npm/_logs/2022-12-08T18_09_14_471Z-debug.log
```

The verbose logs are below:

```
#9 3.056 738 silly postinstall lightningcss-cli-linux-x64-gnu@1.17.1
#9 3.056 739 info lifecycle lightningcss-cli-linux-x64-gnu@1.17.1~postinstall: lightningcss-cli-linux-x64-gnu@1.17.1
#9 3.056 740 silly postinstall lightningcss-cli-linux-x64-musl@1.17.1
#9 3.056 741 info lifecycle lightningcss-cli-linux-x64-musl@1.17.1~postinstall: lightningcss-cli-linux-x64-musl@1.17.1
#9 3.056 742 silly postinstall lightningcss-cli@1.17.1
#9 3.056 743 info lifecycle lightningcss-cli@1.17.1~postinstall: lightningcss-cli@1.17.1
#9 3.056 744 verbose lifecycle lightningcss-cli@1.17.1~postinstall: unsafe-perm in lifecycle false
#9 3.056 745 verbose lifecycle lightningcss-cli@1.17.1~postinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/lightningcss-cli/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
#9 3.056 746 verbose lifecycle lightningcss-cli@1.17.1~postinstall: CWD: /usr/lib/node_modules/lightningcss-cli
#9 3.056 747 silly lifecycle lightningcss-cli@1.17.1~postinstall: Args: [ '-c', 'node postinstall.js' ]
#9 3.056 748 silly lifecycle lightningcss-cli@1.17.1~postinstall: Returned: code: 1  signal: null
#9 3.056 749 info lifecycle lightningcss-cli@1.17.1~postinstall: Failed to exec postinstall script
#9 3.056 750 timing action:postinstall Completed in 62ms
#9 3.056 751 verbose unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
#9 3.056 752 timing stage:rollbackFailedOptional Completed in 6ms
#9 3.056 753 timing stage:runTopLevelLifecycles Completed in 2384ms
#9 3.056 754 warn optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-cli-linux-arm64-gnu@1.17.1 (node_modules/lightningcss-cli/node_modules/lightningcss-cli-linux-arm64-gnu):
#9 3.056 755 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-cli-linux-arm64-gnu@1.17.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
#9 3.056 756 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    linux
#9 3.056 756 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  arm64
#9 3.056 756 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
#9 3.056 756 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
#9 3.056 757 warn optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-cli-darwin-x64@1.17.1 (node_modules/lightningcss-cli/node_modules/lightningcss-cli-darwin-x64):
#9 3.056 758 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-cli-darwin-x64@1.17.1: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
#9 3.056 759 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
#9 3.056 759 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  x64
#9 3.056 759 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
#9 3.056 759 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
#9 3.056 760 warn optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-cli-linux-arm64-musl@1.17.1 (node_modules/lightningcss-cli/node_modules/lightningcss-cli-linux-arm64-musl):
#9 3.056 761 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-cli-linux-arm64-musl@1.17.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
#9 3.056 762 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    linux
#9 3.056 762 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  arm64
#9 3.056 762 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
#9 3.056 762 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
#9 3.056 763 warn optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-cli-linux-arm-gnueabihf@1.17.1 (node_modules/lightningcss-cli/node_modules/lightningcss-cli-linux-arm-gnueabihf):
#9 3.056 764 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-cli-linux-arm-gnueabihf@1.17.1: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
#9 3.056 765 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    linux
#9 3.056 765 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  arm
#9 3.056 765 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
#9 3.056 765 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
#9 3.056 766 warn optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-cli-darwin-arm64@1.17.1 (node_modules/lightningcss-cli/node_modules/lightningcss-cli-darwin-arm64):
#9 3.056 767 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-cli-darwin-arm64@1.17.1: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
#9 3.056 768 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
#9 3.056 768 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  arm64
#9 3.056 768 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
#9 3.056 768 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
#9 3.056 769 warn optional SKIPPING OPTIONAL DEPENDENCY: lightningcss-cli-win32-x64-msvc@1.17.1 (node_modules/lightningcss-cli/node_modules/lightningcss-cli-win32-x64-msvc):
#9 3.056 770 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for lightningcss-cli-win32-x64-msvc@1.17.1: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
#9 3.056 771 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    win32
#9 3.056 771 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  x64
#9 3.056 771 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
#9 3.056 771 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
#9 3.056 772 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/sass/node_modules/chokidar/node_modules/fsevents):
#9 3.056 773 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
#9 3.056 774 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
#9 3.056 774 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
#9 3.056 774 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
#9 3.056 774 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
#9 3.056 775 verbose stack Error: lightningcss-cli@1.17.1 postinstall: `node postinstall.js`
#9 3.056 775 verbose stack Exit status 1
#9 3.056 775 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
#9 3.056 775 verbose stack     at EventEmitter.emit (events.js:400:28)
#9 3.056 775 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
#9 3.056 775 verbose stack     at ChildProcess.emit (events.js:400:28)
#9 3.056 775 verbose stack     at maybeClose (internal/child_process.js:1088:16)
#9 3.056 775 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
#9 3.056 776 verbose pkgid lightningcss-cli@1.17.1
#9 3.056 777 verbose cwd /
#9 3.056 778 verbose Linux 5.15.79.1-microsoft-standard-WSL2
#9 3.056 779 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--global" "sass" "lightningcss-cli"
#9 3.056 780 verbose node v14.21.1
#9 3.056 781 verbose npm  v6.14.17
#9 3.056 782 error code ELIFECYCLE
#9 3.056 783 error errno 1
#9 3.056 784 error lightningcss-cli@1.17.1 postinstall: `node postinstall.js`
#9 3.056 784 error Exit status 1
#9 3.056 785 error Failed at the lightningcss-cli@1.17.1 postinstall script.
#9 3.056 785 error This is probably not a problem with npm. There is likely additional logging output above.
#9 3.056 786 verbose exit [ 1, true ]
------
executor failed running [/bin/sh -c USER=root npm install --global sass lightningcss-cli; cat /root/.npm/_logs/*.log; exit 1]: exit code: 1
```

I suspect the postinstall script needs to be updated to handle WSL2's linux version so it can find the right linux binary to run.

I do have a workaround so this isn't urgent for me. I was able to use the following in my Dockerfile:

```
RUN USER=root npm install --global --ignore-scripts lightningcss-cli; cp /usr/lib/node_modules/lightningcss-cli/node_modules/lightningcss-cli-linux-x64-gnu/lightningcss /usr/local/bin/
```

**Comment by devongovett** [comment]
Looks like `lightningcss-cli-linux-x64-gnu` was installed, but it couldn't copy/link the files into the right place. You could try logging the error here https://github.com/parcel-bundler/lightningcss/blob/27cb9c2a382fd8d9702de8def9dd18db54280c43/cli/postinstall.js#L36

**Comment by mhlakhani** [comment]
That error does show up in the logs, you're right! I think the check https://github.com/parcel-bundler/lightningcss/blob/27cb9c2a382fd8d9702de8def9dd18db54280c43/cli/postinstall.js#L4-L16 needs to be updated.

**Comment by devongovett** [comment]
Could you log out what `err` is there?

**Comment by mhlakhani** [comment]
@devongovett I can give it a shot, but I'm not sure how to get a repro that runs *within* the docker build and my modified code version (I can't repro on the host machine). do you have any tips handy? I'll try searching otherwise and that might take me a bit

**Comment by mortifia** [comment]
to reproduce
- vscode wsl to repo in wsl
- ubuntu-22.04 (wsl)
- in vs code terminal
    ```sh
    docker compose -f "docker-compose.yml" up -d --build 
    ```
> docker-compose.yml
```yml
build: ./xxxxxx
volumes:
      - ./xxxxxx/:/app
      - '/app/node_modules' # to avoid acess to local node_modules in container
```
> Dockerfile
```Dockerfile
# run node
FROM node:18-alpine
# set working directory
WORKDIR /app
# copy package.json
COPY package.json ./
# COPY package-lock.json ./

# install dependencies
RUN npm install

EXPOSE 3001
#finish
CMD ["npm", "run", "dev"]
```
> .dockerignore
```.dockerignore
node_modules
```
- in container 
```console
/app # ls -la
total 184
drwxr-xr-x    6 node     node          4096 Jan 11 13:31 .
drwxr-xr-x    1 root     root          4096 Jan 11 13:48 ..
-rw-r--r--    1 node     node            12 Jan 11 13:03 .dockerignore
-rw-r--r--    1 node     node            40 Jan 11 13:03 .gitignore
-rw-r--r--    1 node     node           324 Jan 11 13:45 Dockerfile
drwxr-xr-x  160 root     root          4096 Jan 11 13:44 node_modules
-rw-r--r--    1 node     node        132026 Jan 11 13:31 package-lock.json
-rw-r--r--    1 node     node           736 Jan 11 13:03 package.json
drwxr-xr-x    2 node     node          4096 Jan 11 13:03 src
-rw-r--r--    1 node     node         11109 Jan 11 13:03 tsconfig.json
drwxr-xr-x    2 node     node          4096 Jan 11 13:03 types
/app #
```

**Comment by mortifia** [comment]
set `USER node` before `RUN npm install`
```
#0 70.37 npm notice 
#0 70.37 npm notice New major version of npm available! 8.19.3 -> 9.2.0
#0 70.37 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.2.0>
#0 70.37 npm notice Run `npm install -g npm@9.2.0` to update!
#0 70.37 npm notice 
#0 70.38 npm ERR! code EACCES
#0 70.38 npm ERR! syscall mkdir
#0 70.38 npm ERR! path /app/node_modules
#0 70.38 npm ERR! errno -13
#0 70.38 npm ERR! Error: EACCES: permission denied, mkdir '/app/node_modules'
#0 70.38 npm ERR!  [Error: EACCES: permission denied, mkdir '/app/node_modules'] {
#0 70.38 npm ERR!   errno: -13,
#0 70.38 npm ERR!   code: 'EACCES',
#0 70.38 npm ERR!   syscall: 'mkdir',
#0 70.38 npm ERR!   path: '/app/node_modules'
#0 70.38 npm ERR! }
#0 70.38 npm ERR! 
#0 70.38 npm ERR! The operation was rejected by your operating system.
#0 70.38 npm ERR! It is likely you do not have the permissions to access this file as the current user
#0 70.38 npm ERR! 
#0 70.38 npm ERR! If you believe this might be a permissions issue, please double-check the
#0 70.38 npm ERR! permissions of the file and its containing directories, or try running
#0 70.38 npm ERR! the command again as root/Administrator.
#0 70.38 
#0 70.38 npm ERR! A complete log of this run can be found in:
#0 70.38 npm ERR!     /home/node/.npm/_logs/2023-01-11T14_11_07_221Z-debug-0.log```

**Comment by Brooooooklyn** [comment]
@mhlakhani this is absolutely an npm bug, I can reproduce it in `rust:latest` image. You can upgrade the npm client in Dockerfile after Node.js is installed: `npm i -g npm` and this issue will disappear.

**Comment by mortifia** [comment]
@Brooooooklyn 
thanks it's work !
