### ISSUE TITLE
@parcel/transformer-css: Unexpected token '.'

### ISSUE THREAD

**Issue by hequ** [parcel-bundler/lightningcss#438]
Hi!

I created a new project from scratch and tried to add a simple .css file to my index.html page. When trying to build the project with `parcel 2.8.3` I got the error: `@parcel/transformer-css: Unexpected token '.'`.

node version: `v18.14.2` and `v19.7.0`

Here are the relevant files:

package.json
```js 
{
  "devDependencies": {
    "parcel": "2.8.3"
  },
  "source": "src/index.html",
  "scripts": {
    "start": "parcel"
  }
}

```

index.html

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Test Site</title>
    <link href="styles/app.css" />
</head>
<body>
<h1>Test</h1>
</body>
</html>
```

app.css

```css
body {
    margin: 80px;
}
```

When running this, I get:
```
> start
> parcel

Server running at http://localhost:1234
🚨 Build failed.

@parcel/transformer-css: Unexpected token '.'

  /Users/xyz/Projects/test/frontend/node_modules/lightningcss/node/composeVisitors.js:67
        return v?.(item.value);
                 ^

  SyntaxError: Unexpected token '.'
      at wrapSafe (internal/modules/cjs/loader.js:915:16)
      at Module._compile (internal/modules/cjs/loader.js:963:27)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at NodePackageManager.load (/Users/xyz/Projects/test/frontend/node_modules/@parcel/package-manager/lib/index.js:3375:15)
      at NodePackageManager.requireSync (/Users/xyz/Projects/test/frontend/node_modules/@parcel/package-manager/lib/index.js:3353:21)
      at Module.m.require (/Users/xyz/Projects/test/frontend/node_modules/@parcel/package-manager/lib/index.js:3366:25)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (/Users/xyz/Projects/test/frontend/node_modules/lightningcss/node/index.js:26:34)
      at Module._compile (internal/modules/cjs/loader.js:999:30)
```

If I downgrade lightningcss to `1.17` then this error goes away. This error seems to occur with lightningcss `1.18` and `1.19`. I didn't find an issue about this, but if this is a duplicate, please feel free to close.

**Comment by mischnic** [comment]
Which Node version are you using?

**Comment by hequ** [comment]
> Which Node version are you using?

I tried with `v18.14.2` and `v19.7.0` and happens with them both.

**Comment by mgiraldo** [comment]
i'm having this same issue on macos ventura 13.2.1, node v16.19.0 npm v8.19.3, and also with node v14.21.2 npm v6.14.17

**Comment by mischnic** [comment]
The reason I asked was because your Node version might not support optional chaining, but Node >= 16 does have it. So not  sure what's happening here.

**Comment by mgiraldo** [comment]
ok with node v16.14.2 and npm 8.5.0 i finally got it to build 😅
