### ISSUE TITLE
Some tests not passing on local Windows build

### ISSUE THREAD

**Issue by marcuspang** [parcel-bundler/lightningcss#541]
While running `yarn test` and `cargo test`, I ran into some minor test errors.

For `yarn test`, 

```
bundle.test.mjs
✘ ✘ • • • • • • • • • • • •   (12 / 14)

   FAIL  "resolver"
    Could not find hello/world.css in foo.css, bar.css, hello/world.css.

    at read (.../lightning-css/node/test/bundle.test.mjs:31:28)


   FAIL  "only custom read"
    Could not find hello/world.css in foo.css, hello/world.css, bar.css.

    at read (.../lightning-css/node/test/bundle.test.mjs:82:28)
```

For `cargo test`,
```
failures:

---- tests::test_color_mix stdout ----
thread 'tests::test_color_mix' panicked at 'assertion failed: `(left == right)`
  left: `".foo{color:lch(79.7255% 40.4543 84.7634)}"`,
 right: `".foo{color:lch(79.7255% 40.4542 84.7634)}"`', src/lib.rs:93:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- bundler::tests::test_css_module stdout ----
thread 'bundler::tests::test_css_module' panicked at 'assertion failed: `(left == right)`
  left: `".aqyBbW_b {\n  background: #ff0;\n}\n\n.eoHolq_a {\n  background: #fff;\n}\n"`,
 right: `".dyGcAa_b {\n  background: #ff0;\n}\n\n.CK9avG_a {\n  background: #fff;\n}\n"`', src\bundler.rs:1955:5

---- tests::test_css_modules stdout ----
thread 'tests::test_css_modules' panicked at 'assertion failed: `(left == right)`
  left: `".Ot1kIW_foo {\n  background: red;\n}\n"`,
 right: `".EgL3uq_foo {\n  background: red;\n}\n"`', src/lib.rs:22841:7

---- tests::test_relative_color stdout ----
thread 'tests::test_relative_color' panicked at 'assertion failed: `(left == right)`
  left: `".foo{color:lch(63.9252% 51.2777 26.8448)}"`,
 right: `".foo{color:lch(63.9252% 51.2776 26.8448)}"`', src/lib.rs:93:5

---- tests::test_gradients stdout ----
thread 'tests::test_gradients' panicked at 'assertion failed: `(left == right)`
  left: `".foo {\n  background: linear-gradient(#ff0f0e, #7773ff);\n  background: linear-gradient(color(display-p3 1 .0000153435 -.00000303562), color(display-p3 .44029 .28452 1.23485));\n  background: linear-gradient(lch(56.208% 136.76 46.312), lch(51% 135.366 301.364));\n}\n"`,
 right: `".foo {\n  background: linear-gradient(#ff0f0e, #7773ff);\n  background: linear-gradient(color(display-p3 1 .0000153435 -.00000303562), color(display-p3 .440289 .28452 1.23485));\n  background: linear-gradient(lch(56.208% 136.76 46.312), lch(51% 135.366 301.364));\n}\n"`', src/lib.rs:110:5
```

## Local Versions

Windows: Version 22H2 (OS Build 22621.1848)
Node: 18.13.0
cargo: cargo 1.70.0 (ec8a8a0ca 2023-04-25)

**Comment by marcuspang** [comment]
Seem like minor issues, will try and resolve them

**Comment by Netail** [comment]
Some decimal roundings & moduled-css hashes differ (I assume it's because the hash is calculated with the path, where Linux/Macos paths contain `/` and Windows `\`)

**Comment by Jungzl** [comment]
The precision differences (e.g., `40.4542` vs `40.4543`) are caused by **platform-specific math functions** in color space conversions. This is expected behavior.

Color conversions use trigonometric functions ([`sin`](https://github.com/parcel-bundler/lightningcss/blob/master/src/values/color.rs#L1881), [`cos`](https://github.com/parcel-bundler/lightningcss/blob/master/src/values/color.rs#L1880), [`atan2`](https://github.com/parcel-bundler/lightningcss/blob/master/src/values/color.rs#L1868)) which have ["unspecified precision"](https://doc.rust-lang.org/std/primitive.f32.html#method.atan2) and call platform libc:
- Windows MSVC vs Linux glibc produce slightly different results
- According to [Rust core contributors](https://users.rust-lang.org/t/question-on-unspecified-precision/116636/2), only `+ - * / % √` are deterministic across platforms
