### ISSUE TITLE
Importing radix colors breaks build

### ISSUE THREAD

**Issue by mrmartineau** [parcel-bundler/lightningcss#768]
I am trying to import some Radix UI colors but it breaking my build.

Radix colors have been installed to my project: `yarn add @radix-ui/colors`

Here's my source file:

```css
/* colors.css */
@import '@radix-ui/colors/gray.css';

:root {
  --color-brand-blue: blue;
  --color-brand-navy: navy;
}
```

Here's my build script:

```js
import {
  bundle,
  browserslistToTargets
} from 'lightningcss';
import fs from 'node:fs';
import browserslist from 'browserslist';

const bundleCSS = (entry, out, minify = false) => {
  let { code, map } = bundle({
    filename: entry,
    minify,
    sourceMap: true,
    targets: browserslistToTargets(browserslist('defaults'))
  });

  code = code.toString()

  if (map) {
    code = `${code}\n/*# sourceMappingURL=${out}.css.map */\n`;
  }

  fs.writeFileSync(`./dist/${out}.css`, code);

  if (map) {
    fs.writeFileSync(`./dist/${out}.css.map`, map);
  }
}

console.time('\n👷‍♀️ Bundled Styles');


bundleCSS('./src/tokens/colors.css', 'colors.min', true);

console.timeEnd('\n👷‍♀️ Bundled Styles')
```

I get this error when the `@import '@radix-ui/colors/gray.css';` line is added:

```
file:///Users/zmartineau/code/dare/node-libs/packages/styles/build.js:9
  let { code, map } = bundle({
                      ^

SyntaxError: No such file or directory (os error 2)
    at bundleCSS (file:///Users/mrmartineau/code/styles/build.js:9:23)
    at file:///Users/mrmartineau/code/styles/build.js:31:1
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:485:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:109:5) {
  fileName: './src/tokens/colors.css',
  loc: { line: 1, column: 1 },
  data: 'ResolverError'
}

Node.js v22.4.0
```

Does Lightning support this?

**Comment by mrmartineau** [comment]
Hi @devongovett, thanks for your response, is there not a resolver that already exists? If not, I will see if I get the time to create one, so for now I have inlined some of the Radix colours.
