### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by rgpublic** [parcel-bundler/lightningcss#791]
I get just a segmentation fault for this input:

```
p {
    max-width: calc(2 * min(1px, 1vmin) - min(1px, 1vmin));
}
```

**Comment by ColonelThirtyTwo** [comment]
Getting this too:

```js
import { transform } from 'lightningcss';

let { code, map } = transform({
  filename: 'style.css',
  code: Buffer.from('p { max-width: calc(2 * min(1px, 1vmin) - min(1px, 1vmin)); }'),
  minify: true,
  sourceMap: true
});
```

Looks like overflowing the stack:

```
#40221 0x00007fffecfeeec8 in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40222 0x00007fffecfefb0b in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40223 0x00007fffecfeeec8 in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40224 0x00007fffecfefb0b in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40225 0x00007fffecfeeec8 in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40226 0x00007fffecfefb0b in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40227 0x00007fffecfeeec8 in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40228 0x00007fffecfefb0b in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40229 0x00007fffecfeeec8 in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40230 0x00007fffecfd5ae5 in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40231 0x00007fffecfd44ce in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40232 0x00007fffeceb5731 in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40233 0x00007fffece8851e in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40234 0x00007fffece73790 in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40235 0x00007fffece705bd in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40236 0x00007fffed17b4f6 in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40237 0x00007fffed5a42d4 in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40238 0x00007fffed5295ab in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40239 0x00007fffece417d6 in ?? () from /home/col/Downloads/lightningcss-test/node_modules/lightningcss-linux-x64-gnu/lightningcss.linux-x64-gnu.node
#40240 0x0000555555f27129 in operator() (__closure=<optimized out>, env=0x555558e51240) at ../src/js_native_api_v8.cc:503
#40241 napi_env__::CallIntoModule<v8impl::(anonymous namespace)::FunctionCallbackWrapper::InvokeCallback()::<lambda(napi_env)>, v8impl::(anonymous namespace)::FunctionCallbackWrapper::InvokeCallback()::<lambda(napi_env, v8::Local<v8::Value>)> > (this=0x555558e51240, call=..., handle_exception=...) at ../src/js_native_api_v8.h:93
#40242 v8impl::(anonymous namespace)::FunctionCallbackWrapper::InvokeCallback (this=0x7fffffffc470) at ../src/js_native_api_v8.cc:503
#40243 v8impl::(anonymous namespace)::FunctionCallbackWrapper::Invoke (info=...) at ../src/js_native_api_v8.cc:425
#40244 0x00005554f6e4f6e2 in ?? ()
```
Arch Linux, node v22.8.0, npm v10.8.3

I'm also experiencing segmentation fault when trying to build backrest, which may be related: https://github.com/garethgeorge/backrest/issues/463
